#include "editor_utils\functions.hpp"
#include "kp_plm\KPPLM_functions.hpp"

class SPEC {
    #include "arsenal_02\functions.hpp"
    #include "cbps_deploy\functions.hpp"
    #include "btc_hm_stuff\functions.hpp"
    #include "rabbit_support\functions.hpp"
    #include "other_missions\functions.hpp"
    #include "radio_chatter\functions.hpp"
    #include "jammer\functions.hpp"
    #include "halo_restrict\functions.hpp"
    #include "ambient_music\functions.hpp"
};
