#include "specbased\editor_utils\functions.hpp"
#include "specbased\kp_plm\KPPLM_functions.hpp"

class SPEC {
    #include "specbased\arsenal_02\functions.hpp"
    #include "specbased\cbps_deploy\functions.hpp"
    #include "specbased\btc_hm_stuff\functions.hpp"
    #include "specbased\rabbit_support\functions.hpp"
    #include "specbased\other_missions\functions.hpp"
    #include "specbased\radio_chatter\functions.hpp"
    #include "specbased\jammer\functions.hpp"
    #include "specbased\halo_restrict\functions.hpp"
    #include "specbased\ambient_music\functions.hpp"
};
