loadScreen = "specbased\mission_frameworks\btc_hearts_and_minds\core\img\btc.paa";

#include "specbased\mission_frameworks\btc_hearts_and_minds\core\fnc\common\dlg.hpp"
#include "specbased\mission_frameworks\btc_hearts_and_minds\core\fnc\fob\dlg.hpp"
#include "specbased\mission_frameworks\btc_hearts_and_minds\core\fnc\log\dlg.hpp"
#include "specbased\mission_frameworks\btc_hearts_and_minds\core\fnc\debug\defines.hpp"

#include "specbased\mission_frameworks\btc_hearts_and_minds\core\def\param.hpp"
#include "specbased\mission_frameworks\btc_hearts_and_minds\core\fnc\mil\aiskill.hpp"
#include "specbased\mission_frameworks\btc_hearts_and_minds\core\fnc\task\taskTypes.hpp"
